FROM dmotte/desktainer

#TODO

#TODO sshd + siab + browser + other packages see t.o.Dockerfile and various p.b.
#TODO install procps
#TODO append sshd to supervisord.conf
#TODO desktop background color?
